In [1]:
import numpy as np

In [2]:
s=5  #escalar
s

5

In [3]:
x=np.array([5,-2,4]) #vector
x

array([ 5, -2,  4])

In [6]:
m=np.array([[5,12,6],[-3,0,14]]) #esto es una matriz  de 2x3
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [8]:
type(s)


int

In [9]:
type(m)

numpy.ndarray

In [11]:
n_array=np.array(7) #esto es un escalar otra forma de escribirlo 
n_array

array(7)

In [12]:
m.shape
#nos muestra el tamaño de nuestra matriz 

(2, 3)

In [15]:
x.reshape(1,3)#nos da un vector fila

array([[ 5, -2,  4]])

In [16]:
x.reshape(3,1)#nos da un vector columna 

array([[ 5],
       [-2],
       [ 4]])

In [17]:
m1=np.array([[5,12,0],[-3,0,14]])
m1

array([[ 5, 12,  0],
       [-3,  0, 14]])

In [18]:
m2=np.array([[9,8,7],[1,3,5]])
m2

array([[9, 8, 7],
       [1, 3, 5]])

In [19]:
t=np.array([m1,m2])
t

array([[[ 5, 12,  0],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3,  5]]])

In [21]:
t.shape #tiene 2matrices de 2x3

(2, 2, 3)

In [24]:
#tensor manual 
t_manual=np.array([[[5,1,4],[7,8,5]],[[7,2,8],[1,5,2]]])
t_manual

array([[[5, 1, 4],
        [7, 8, 5]],

       [[7, 2, 8],
        [1, 5, 2]]])

In [25]:
#suma de matrices
m1+m2

array([[14, 20,  7],
       [-2,  3, 19]])

In [26]:
m1-m2

array([[-4,  4, -7],
       [-4, -3,  9]])

In [27]:
v1=np.array([1,4,7,8,9])
v2=np.array([2,3,1,5,6])

In [28]:
v1+v2  #suma de vectores 

array([ 3,  7,  8, 13, 15])

In [31]:
y=np.array([1,2,5])
y

array([1, 2, 5])

In [32]:
y +1 #suma un escalar a un vector 

array([2, 3, 6])

In [33]:
z= np.array([[2,3,4,4],[4,6,6,7]])
z

array([[2, 3, 4, 4],
       [4, 6, 6, 7]])

In [34]:
z +1 #suma de 1 escalar a una matriz de 2x4

array([[3, 4, 5, 5],
       [5, 7, 7, 8]])

In [35]:
#matriz transpuesta 
A=np.array([[5,12,6],[3,0,14]])
A

array([[ 5, 12,  6],
       [ 3,  0, 14]])

In [36]:
A.T #esto me muetsra la matriz transpuesta 

array([[ 5,  3],
       [12,  0],
       [ 6, 14]])

In [37]:
s=np.array([1,2,4])
s

array([1, 2, 4])

In [38]:
s.T #los vectores en python no se transponen

array([1, 2, 4])

In [39]:
#producto de matrices 
a=np.array([1,2,3])
b=np.array([2,3,4])

In [40]:
np.dot(a,b) #metodo de dot de numpy para producto

20

In [41]:
np.dot(7,7) #producto de 2 escalares 

49

In [42]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [43]:
5*c #producto de 1 vector 

array([ 5, 10, 15])

In [44]:
q=np.array([[1,3,2],[4,5,6]])
q

array([[1, 3, 2],
       [4, 5, 6]])

In [45]:
3*q #producto de una matriz

array([[ 3,  9,  6],
       [12, 15, 18]])

In [47]:
#producto de 2 matrices tienen en todos los casos la misma dimension .-
s=np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
s1=np.array([[1,2],[3,4],[5,6]])
s1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np.dot(s,s1)

array([[22, 28],
       [49, 64]])

In [52]:
e=np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,6]])
e
            

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,   6]])

In [53]:
e1=np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
e1

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [54]:
np.dot(e,e1)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 23, -51]])