In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
import seaborn as sns 
sns.set()

In [2]:
new_data=pd.read_csv('2.02. Binary predictors.csv')
new_data

SAT Admitted  Gender
0    1363       No    Male
1    1792      Yes  Female
2    1954      Yes  Female
3    1653       No    Male
4    1593       No    Male
..    ...      ...     ...
163  1722      Yes  Female
164  1750      Yes    Male
165  1555       No    Male
166  1524       No    Male
167  1461       No    Male

[168 rows x 3 columns]

In [4]:
data=new_data.copy()
data['Admitted']=data['Admitted'].map({'Yes':1,'No':0})
data['Gender']=data['Gender'].map({'Female':1,'Male':0})
data

SAT  Admitted  Gender
0    1363         0       0
1    1792         1       1
2    1954         1       1
3    1653         0       0
4    1593         0       0
..    ...       ...     ...
163  1722         1       1
164  1750         1       0
165  1555         0       0
166  1524         0       0
167  1461         0       0

[168 rows x 3 columns]

In [5]:
y=data['Admitted']
x1=data['Gender']


In [6]:
x=sm.add_constant(x1)
reg_log=sm.Logit(y,x)
results_log=reg_log.fit()
results_log.summary()

Optimization terminated successfully.
         Current function value: 0.572260
         Iterations 5


C:\Users\Lenovo\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Admitted   No. Observations:                  168
Model:                          Logit   Df Residuals:                      166
Method:                           MLE   Df Model:                            1
Date:                Wed, 02 Feb 2022   Pseudo R-squ.:                  0.1659
Time:                        19:08:55   Log-Likelihood:                -96.140
converged:                       True   LL-Null:                       -115.26
Covariance Type:            nonrobust   LLR p-value:                 6.283e-10
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6436      0.222     -2.901      0.004      -1.078      -0.209
Gender         2.0786      0.363      5.727      0.000       1.367       2.790
==============================================================================
"""

In [7]:
np.exp(2.0786)#exponencial de la mujer es 7.99 veces mayor que la de un hombre

7.993270498536442

In [8]:
np.set_printoptions(formatter={'float':lambda x:"{0:0.2f}".format(x)})
results_log.predict()

array([0.34, 0.81, 0.81, 0.34, 0.34, 0.81, 0.81, 0.81, 0.81, 0.34, 0.81,
       0.81, 0.81, 0.34, 0.34, 0.81, 0.34, 0.34, 0.81, 0.81, 0.81, 0.34,
       0.81, 0.81, 0.81, 0.34, 0.81, 0.34, 0.81, 0.81, 0.34, 0.81, 0.34,
       0.34, 0.34, 0.34, 0.34, 0.81, 0.34, 0.81, 0.34, 0.81, 0.34, 0.34,
       0.34, 0.34, 0.81, 0.34, 0.34, 0.34, 0.34, 0.34, 0.81, 0.81, 0.81,
       0.34, 0.34, 0.81, 0.34, 0.81, 0.34, 0.34, 0.81, 0.34, 0.34, 0.34,
       0.34, 0.34, 0.81, 0.34, 0.34, 0.34, 0.81, 0.34, 0.34, 0.34, 0.34,
       0.34, 0.81, 0.81, 0.34, 0.81, 0.81, 0.81, 0.81, 0.81, 0.34, 0.34,
       0.81, 0.81, 0.81, 0.81, 0.81, 0.81, 0.34, 0.34, 0.81, 0.81, 0.81,
       0.81, 0.81, 0.34, 0.81, 0.34, 0.81, 0.81, 0.81, 0.81, 0.34, 0.34,
       0.34, 0.34, 0.34, 0.81, 0.34, 0.34, 0.81, 0.34, 0.81, 0.81, 0.81,
       0.34, 0.81, 0.34, 0.81, 0.34, 0.81, 0.34, 0.34, 0.34, 0.81, 0.34,
       0.81, 0.34, 0.34, 0.34, 0.81, 0.34, 0.81, 0.34, 0.34, 0.81, 0.34,
       0.81, 0.81, 0.81, 0.34, 0.34, 0.34, 0.34, 0.

In [9]:
np.array(data['Admitted'])

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [10]:
results_log.pred_table() #crea una tabla

array([[59.00, 15.00],
       [31.00, 63.00]])

In [12]:
cm_df=pd.DataFrame(results_log.pred_table())
cm_df.columns=['Predict 0','Predict 1']
cm_df=cm_df.rename(index={0:'actual 0', 1:'actual 1'})
cm_df

Predict 0  Predict 1
actual 0       59.0       15.0
actual 1       31.0       63.0

## Para 59 observaciones le modelo predijo 0,
## el valor real era 0
## para 63 observaciones el modelo predijo 1 , 
## cuando el valor real era 1
## para 31 observaciones el modelo predijo 0 cuando el valor era 1
## para 15 observaciones el modelo predijo 1 cuando era 0

## calculamos la precision del modelo 

In [13]:
cm=np.array(cm_df)
accuracy_train=(cm[0,0]+cm[1,1])/cm.sum()
accuracy_train

0.7261904761904762